-- Create pdf_artifacts table for storing PDF artifact references
-- Uses the existing organization-assets bucket for storage
CREATE TABLE IF NOT EXISTS pdf_artifacts (
  id TEXT PRIMARY KEY,
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  conversation_id TEXT,
  department_id TEXT,
  task_id TEXT,
  result_id TEXT,
  origin TEXT,
  filename TEXT NOT NULL,
  mime_type TEXT NOT NULL DEFAULT 'application/pdf',
  size_bytes INTEGER NOT NULL,
  storage_path TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Constraints
  CONSTRAINT pdf_artifacts_mime_type_check CHECK (mime_type = 'application/pdf'),
  CONSTRAINT pdf_artifacts_size_bytes_check CHECK (size_bytes > 0 AND size_bytes <= 10485760) -- 10 MB max
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_pdf_artifacts_organization_id ON pdf_artifacts(organization_id);
CREATE INDEX IF NOT EXISTS idx_pdf_artifacts_conversation_id ON pdf_artifacts(conversation_id);
CREATE INDEX IF NOT EXISTS idx_pdf_artifacts_created_at ON pdf_artifacts(created_at DESC);

-- Enable RLS
ALTER TABLE pdf_artifacts ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
-- Policy: Users can only see PDFs from their own organization
CREATE POLICY "Users can view own organization PDFs" ON pdf_artifacts
  FOR SELECT
  USING (
    organization_id IN (
      SELECT organization_id FROM organization_memberships
      WHERE user_id = auth.uid()
    )
  );

-- Policy: Users can insert PDFs for their own organization
CREATE POLICY "Users can insert own organization PDFs" ON pdf_artifacts
  FOR INSERT
  WITH CHECK (
    organization_id IN (
      SELECT organization_id FROM organization_memberships
      WHERE user_id = auth.uid()
    )
  );

-- Policy: Users can delete PDFs from their own organization
CREATE POLICY "Users can delete own organization PDFs" ON pdf_artifacts
  FOR DELETE
  USING (
    organization_id IN (
      SELECT organization_id FROM organization_memberships
      WHERE user_id = auth.uid()
    )
  );

-- Service role can do everything (for backend operations)
CREATE POLICY "Service role can manage all PDFs" ON pdf_artifacts
  FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- Add storage policy for PDF artifacts in organization-assets bucket
-- PDFs are stored at: organizations/<organizationId>/pdf-artifacts/<id>.pdf
CREATE POLICY "Users can view own organization PDF files" ON storage.objects
  FOR SELECT
  USING (
    bucket_id = 'organization-assets' AND
    (storage.foldername(name))[1] = 'organizations' AND
    (storage.foldername(name))[2] IN (
      SELECT organization_id::text FROM organization_memberships
      WHERE user_id = auth.uid()
    ) AND
    (storage.foldername(name))[3] = 'pdf-artifacts'
  );

CREATE POLICY "Users can upload own organization PDF files" ON storage.objects
  FOR INSERT
  WITH CHECK (
    bucket_id = 'organization-assets' AND
    (storage.foldername(name))[1] = 'organizations' AND
    (storage.foldername(name))[2] IN (
      SELECT organization_id::text FROM organization_memberships
      WHERE user_id = auth.uid()
    ) AND
    (storage.foldername(name))[3] = 'pdf-artifacts'
  );

CREATE POLICY "Users can delete own organization PDF files" ON storage.objects
  FOR DELETE
  USING (
    bucket_id = 'organization-assets' AND
    (storage.foldername(name))[1] = 'organizations' AND
    (storage.foldername(name))[2] IN (
      SELECT organization_id::text FROM organization_memberships
      WHERE user_id = auth.uid()
    ) AND
    (storage.foldername(name))[3] = 'pdf-artifacts'
  );

-- Add comment
COMMENT ON TABLE pdf_artifacts IS 'Stores references to PDF artifacts generated by Departify';
